ignoredBuiltDependencies:
  - '@scarf/scarf'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - core-js-pure
  - esbuild
  - tree-sitter
  - tree-sitter-json
onlyBuiltDependencies:
  - lefthook
useNodeVersion: 21.0.0
